# Generated by Django 2.2.1 on 2019-05-08 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0003_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regimen',
            name='time',
            field=models.IntegerField(default=35),
        ),
    ]
